version: "3"
services:

  pushgateway:
    image: prom/pushgateway:v1.5.1
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:v2.42.0
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    # to enable persistent storage in a volume
    # volumes:
    #   - grafana-storage:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:v0.25.0
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

# volumes:
#   # docker volume create grafana-storage
#   grafana-storage:
#     external: true
